Segtree
rainbou-kpr/library pull request #25
Opened 2023-04-28 02:36 UTC by KowerKoint

セグメント木を作りました。
型指定派と関数オブジェクト渡し派がいるようだったのでmodintを参考にしてCRTPで実装しました。

2023-04-28 07:58 UTC, Raclamusi requested changes

2023-04-28 07:58 UTC, Raclamusi commented on cpp/segtree.hpp
> +    static Op operator_object;
この変数の実体が存在せず、リンクエラーが起こり得ます。これは静的メンバ変数の**宣言**で、別に**定義**が必要です。
C++17 では `inline` をつけるだけでこの問題を回避できます。

```suggestion
    inline static Op operator_object;
```

2023-04-28 07:58 UTC, Raclamusi commented on cpp/segtree.hpp
> +    static std::function<S(S, S)> operator_object;
`std::function` を使うのはオーバーヘッドが気になります……。

2023-04-28 08:28 UTC, KowerKoint commented on cpp/segtree.hpp
> +            if(i != 0) os << ' ';
Vectorもそれになっちゃってるので後で直します…

2023-04-28 08:38 UTC, KowerKoint commented on cpp/segtree.hpp
> +    static Op operator_object;
インライン変数初耳でした:eyes:
理解しましたありがとうございます

2023-04-28 08:40 UTC, KowerKoint commented on cpp/segtree.hpp
> +    static std::function<S(S, S)> operator_object;
opにラムダ式を指定したいという需要を会議でみたんですが、std::function型にオブジェクトをもたせるしかないと思ったのでこうしました。
operator()を持つ型をStaticSegTreeに乗せて使うことで回避できるのでこれはこれであってもいいかなと思っています

2023-04-28 08:42 UTC, KowerKoint commented on cpp/segtree.hpp
> +    static S op(S& a, S& b) { return operator_object(a, b); }
Sの非本質でないメンバ(opの作用時刻とか兄弟のデータとか)をop作用時に変化させたい需要を考えていましたが、やっぱり普通にないのでやめました
そもそもOpがS(S, S)なので呼ばれませんね…

2023-04-28 08:43 UTC, KowerKoint commented on cpp/segtree.hpp
> +    static S op(S& a, S& b) { return operator_object(a, b); }
Op、S(const S&, const S&)にすべき……？

2023-04-28 10:32 UTC, Raclamusi commented on cpp/segtree.hpp
> +    static S op(S& a, S& b) { return operator_object(a, b); }
一般化するなら `S(const S&, const S&)` 、スカラ型に特化するなら `S(S, S)` かな……って感じです。

2023-04-28 11:42 UTC, Raclamusi commented on cpp/segtree.hpp
> +    static std::function<S(S, S)> operator_object;
https://gist.github.com/Raclamusi/6f9793c504eeef2cb90bf42f60f33119
↑
こんな感じで実装して、
```c++
SegTree seg{
    n,
    [](int x, int y) { return std::min(x, y); },
    []() { return std::numeric_limits<int>::max(); }
};
```
のようにコンストラクタにラムダ式を渡すことを考えていました。

うーん、 `std::function` で十分でしょうか……？

このままでいくなら、以下の点の修正をお願いします。

---

https://github.com/rainbou-kpr/library/blob/3c9743ad25b7b91e38a6a76bae49a70bcbfc4567/cpp/segtree.hpp#L241-L242

`inline` をつけてください。

---

https://github.com/rainbou-kpr/library/blob/3c9743ad25b7b91e38a6a76bae49a70bcbfc4567/cpp/segtree.hpp#L263

`e` を参照キャプチャするとダングリング参照が発生する危険性があります。
コピーキャプチャしてください。

2023-04-28 13:07 UTC, KowerKoint commented on cpp/segtree.hpp
> +    static std::function<S(S, S)> operator_object;
https://cpprefjp.github.io/lang/cpp17/type_deduction_for_class_templates.html
こんなのあるんですね…
これがあるならstd::function取り除きます

2023-04-28 14:05 UTC, KowerKoint commented
引数で指定する方式を採用してstd::functionを排除しました。ありがとうございます。

2023-04-29 05:43 UTC, Raclamusi requested changes

2023-04-29 05:43 UTC, Raclamusi commented on cpp/segtree.hpp
> +SegTree(const std::vector<S>&, Op op, const S&) -> SegTree<std::decay_t<S>, Op>;
`std::decay_t` が必要になる場面はおそらくないと思います。

```suggestion
```

2023-04-29 06:57 UTC, Raclamusi commented on cpp/segtree.hpp
> +SegTree(const std::vector<S>&, Op op, const S&) -> SegTree<std::decay_t<S>, Op>;
`std::decay_t` を取る場合、コンストラクタの引数からテンプレート引数を十分に推論できるので、推論補助は必要ありません。

2023-04-29 07:03 UTC, KowerKoint commented on cpp/segtree.hpp
> +SegTree(const std::vector<S>&, Op op, const S&) -> SegTree<std::decay_t<S>, Op>;
たしかに…
削除しました

2023-04-29 07:10 UTC, Raclamusi requested changes

2023-04-29 07:10 UTC, Raclamusi commented on cpp/segtree.hpp
> +    StaticSegTree() = default;
`SegTreeBase` にデフォルトコンストラクタがないため、 `StaticSegTree::StaticSegTree()` および `SegTree::SegTree()` をdefault宣言してもそれを使用することはできません。
`SegTreeBase(int n = 0)` などのようにして、 `SegTreeBase` のデフォルトコンストラクタを用意する必要があります。

2023-04-29 07:10 UTC, Raclamusi commented on cpp/segtree.hpp
> +    explicit SegTree(const std::vector<S>& v, Op op, const S& identity) : SegTree(v.size(), op, identity) {
`op` をムーブするならムーブする、しないならしないで統一しましょう。

```suggestion
    explicit SegTree(int n, Op op, const S& identity) : BaseType(n), operator_object(std::move(op)), identity(identity) {
        this->construct_data();
    }
    /**
     * @brief コンストラクタ
     * 
     * @param v 初期の要素
     * @param op 積の関数オブジェクト
     * @param identity 単位元
     */
    explicit SegTree(const std::vector<S>& v, Op op, const S& identity) : SegTree(v.size(), std::move(op), identity) {
```

2023-04-29 07:15 UTC, KowerKoint commented on cpp/segtree.hpp
> +    StaticSegTree() = default;
抜けてた(う)
ありがとうございます

2023-04-29 08:03 UTC, Raclamusi requested changes

2023-04-29 08:03 UTC, Raclamusi commented on cpp/segtree.hpp
> +        assert(f(e()));
`assert` が定義されていません。
`<cassert>` をインクルードするなどしてください。

2023-04-29 09:26 UTC, Raclamusi requested changes

2023-04-29 09:26 UTC, Raclamusi commented on cpp/segtree.hpp
> +        constexpr S operator() () const { return std::numeric_limits<S>::min(); }
`std::numeric_limits<T>::min()` は、 `T` が浮動小数点型の時に**正**の正規化数の最小値を返します。
本当の（？）最小値が欲しいときは `std::numeric_limits<T>::lowest()` を使います。

```suggestion
        constexpr S operator() () const { return std::numeric_limits<S>::lowest(); }
```

2023-04-29 09:34 UTC, KowerKoint commented on cpp/segtree.hpp
> +        constexpr S operator() () const { return std::numeric_limits<S>::min(); }
罠だ………

2023-04-29 10:18 UTC, Raclamusi approved these changes

2023-04-29 11:49 UTC, merged

2023-04-30 05:03 UTC, Raclamusi commented on cpp/segtree.hpp
> +            if(i != 0) os << ' ';
これ、嘘でした🙇
`CharT != char` でも `char` は出力できるみたいです。
でも、キャストした方が数サイクル速くなると思います。